version: '3'

services:
  tennista.webapi:
    image: tennista.webapi
    build:
      context: ./src/web/Tennista.WebAPI
      dockerfile: Dockerfile

  tennista.webspa:
    image: tennista.webspa
    build:
      context: ./src/web/Tennista.WebSPA
      dockerfile: Dockerfile
      depends_on:
       - tennista.webapi
